import web3 from './web3';
// const { abi, evm } = require('./compile');

const address = "0x2e87c1424D77e63DA756bEb2E46AA036D9C47E58";

console.log(address);

const abi = 
[{"inputs":[],"name":"accountSignUp","outputs":[],"stateMutability":"nonpayable","type":"function","signature":"0x9aadf832"},{"inputs":[],"name":"getAllAccounts","outputs":[{"internalType":"contract MailAccount[]","name":"","type":"address[]"}],"stateMutability":"view","type":"function","constant":true,"signature":"0x08e93d0a"},{"inputs":[{"internalType":"address","name":"addr","type":"address"}],"name":"getMailByAddress","outputs":[{"components":[{"internalType":"string","name":"subject","type":"string"},{"internalType":"address[]","name":"to","type":"address[]"},{"internalType":"address[]","name":"cc","type":"address[]"},{"internalType":"address[]","name":"bcc","type":"address[]"},{"internalType":"string","name":"body","type":"string"},{"internalType":"address","name":"referenceMail","type":"address"}],"internalType":"struct MailObj.Mail","name":"","type":"tuple"}],"stateMutability":"view","type":"function","constant":true,"signature":"0xa94df464"},{"inputs":[],"name":"getRecievedMail","outputs":[{"components":[{"internalType":"string","name":"subject","type":"string"},{"internalType":"address[]","name":"to","type":"address[]"},{"internalType":"address[]","name":"cc","type":"address[]"},{"internalType":"address[]","name":"bcc","type":"address[]"},{"internalType":"string","name":"body","type":"string"},{"internalType":"address","name":"referenceMail","type":"address"}],"internalType":"struct MailObj.Mail[]","name":"","type":"tuple[]"}],"stateMutability":"view","type":"function","constant":true,"signature":"0x68ad47db"},{"inputs":[],"name":"getRecievedMailAddresses","outputs":[{"internalType":"address[]","name":"","type":"address[]"}],"stateMutability":"view","type":"function","constant":true,"signature":"0xb7811900"},{"inputs":[],"name":"getSentMail","outputs":[{"components":[{"internalType":"string","name":"subject","type":"string"},{"internalType":"address[]","name":"to","type":"address[]"},{"internalType":"address[]","name":"cc","type":"address[]"},{"internalType":"address[]","name":"bcc","type":"address[]"},{"internalType":"string","name":"body","type":"string"},{"internalType":"address","name":"referenceMail","type":"address"}],"internalType":"struct MailObj.Mail[]","name":"","type":"tuple[]"}],"stateMutability":"view","type":"function","constant":true,"signature":"0x291ffbe7"},{"inputs":[],"name":"getSentMailAddresses","outputs":[{"internalType":"address[]","name":"","type":"address[]"}],"stateMutability":"view","type":"function","constant":true,"signature":"0x71261f50"},{"inputs":[{"internalType":"address[]","name":"to","type":"address[]"},{"internalType":"string","name":"subject","type":"string"},{"internalType":"string","name":"body","type":"string"}],"name":"sendMail","outputs":[],"stateMutability":"nonpayable","type":"function","signature":"0x6f0cc746"}]

export default new web3.eth.Contract(abi, address);